version: "3.8"


services:
  app:
    image: alexeynaidiuk/fastapi-course
    build: .
    depends_on:
      - mongo
    env_file:
      - ".env"
    restart: always
    ports:
      - "8000:8000"
    networks:
      - 'fastapi-course'
  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongo_data:/data/db
    env_file:
      - ".env"
    restart: always
    networks:
      - 'fastapi-course'
networks:
  fastapi-course:
    name: 'fastapi-course'
    driver: bridge
